'use strict';

const { SecretsManagerClient, GetSecretValueCommand } = require('@aws-sdk/client-secrets-manager');
const mysql = require('mysql2/promise');
const https = require('https');
const url = require('url');

// CloudFormation Custom Resource response helper
async function sendResponse(event, status, reason, data = {}) {
  const responseBody = JSON.stringify({
    Status: status,
    Reason: reason || 'See CloudWatch Logs',
    PhysicalResourceId: event.LogicalResourceId || 'metabase-db-init',
    StackId: event.StackId,
    RequestId: event.RequestId,
    LogicalResourceId: event.LogicalResourceId,
    Data: data,
  });

  const parsedUrl = url.parse(event.ResponseURL);
  const options = {
    hostname: parsedUrl.hostname,
    port: 443,
    path: parsedUrl.path,
    method: 'PUT',
    headers: { 'Content-Type': '', 'Content-Length': responseBody.length },
  };

  return new Promise((resolve, reject) => {
    const req = https.request(options, resolve);
    req.on('error', reject);
    req.write(responseBody);
    req.end();
  });
}

exports.handler = async (event) => {
  console.log('Event:', JSON.stringify(event));

  // Only run on CREATE or UPDATE (when initVersion changes)
  if (event.RequestType === 'Delete') {
    await sendResponse(event, 'SUCCESS', 'Nothing to do on Delete');
    return;
  }

  const sm = new SecretsManagerClient({});

  try {
    // ── 1. Get RDS admin credentials ──────────────────────────────────────────
    const adminSecret = await sm.send(new GetSecretValueCommand({
      SecretId: process.env.ADMIN_SECRET_ARN,
    }));
    const adminCreds = JSON.parse(adminSecret.SecretString);

    // ── 2. Get the Metabase user password (generated by Secrets Manager) ──────
    const metabaseSecret = await sm.send(new GetSecretValueCommand({
      SecretId: process.env.METABASE_SECRET_ARN,
    }));
    const metabaseCreds = JSON.parse(metabaseSecret.SecretString);
    const metabasePassword = metabaseCreds.password;

    if (!metabasePassword) {
      throw new Error('Metabase secret does not contain a password field');
    }

    // ── 3. Connect as RDS admin ────────────────────────────────────────────────
    const conn = await mysql.createConnection({
      host: adminCreds.host,
      port: adminCreds.port || 3306,
      user: adminCreds.username,
      password: adminCreds.password,
      connectTimeout: 30000,
    });

    console.log('Connected to RDS as admin');

    // ── 4. Create metabase_db if it doesn't exist ──────────────────────────────
    await conn.execute(
      "CREATE DATABASE IF NOT EXISTS metabase_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
    );
    console.log('metabase_db created (or already exists)');

    // ── 5. Create metabase_user if it doesn't exist ────────────────────────────
    // Use CREATE USER IF NOT EXISTS to be idempotent
    await conn.execute(
      `CREATE USER IF NOT EXISTS 'metabase_user'@'%' IDENTIFIED BY ?`,
      [metabasePassword]
    );
    console.log('metabase_user created (or already exists)');

    // ── 6. Update password (handles UPDATE event when initVersion changes) ─────
    await conn.execute(
      `ALTER USER 'metabase_user'@'%' IDENTIFIED BY ?`,
      [metabasePassword]
    );

    // ── 7. Grant full privileges on metabase_db ONLY ──────────────────────────
    await conn.execute(
      "GRANT ALL PRIVILEGES ON metabase_db.* TO 'metabase_user'@'%'"
    );

    // ── 8. Flush privileges ────────────────────────────────────────────────────
    await conn.execute('FLUSH PRIVILEGES');

    await conn.end();
    console.log('Metabase DB init complete: metabase_db + metabase_user ready');

    await sendResponse(event, 'SUCCESS', 'metabase_db and metabase_user provisioned successfully');
  } catch (err) {
    console.error('Metabase DB init failed:', err);
    await sendResponse(event, 'FAILED', err.message);
  }
};
