-- =========================================
-- RESET INVENTORY (SAFE RE-RUN)
-- =========================================

DELETE FROM Chambre_Inventory;

-- =========================================
-- GENERATION INVENTORY (30 jours)
-- =========================================

INSERT INTO Chambre_Inventory (chambre_id, date, status)
SELECT
    c.id,
    d.date_day,
    'AVAILABLE'
FROM Chambres c
JOIN (
    SELECT CURDATE() AS date_day
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 1 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 2 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 3 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 4 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 5 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 6 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 7 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 8 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 9 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 10 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 11 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 12 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 13 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 14 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 15 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 16 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 17 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 18 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 19 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 20 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 21 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 22 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 23 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 24 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 25 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 26 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 27 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 28 DAY)
    UNION ALL SELECT DATE_ADD(CURDATE(), INTERVAL 29 DAY)
) d;